# Generated by Django 4.2.4 on 2023-10-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instituicao', models.CharField(max_length=65)),
                ('Imagem', models.ImageField(upload_to='recipes/covers/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50)),
                ('Nome', models.CharField(max_length=50)),
                ('Senha', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=65)),
                ('Instituicao', models.CharField(max_length=65)),
                ('Duracao', models.CharField(max_length=65)),
                ('Categoria', models.CharField(max_length=65)),
                ('Status', models.IntegerField()),
                ('Imagem', models.ImageField(upload_to='recipes/covers/%Y/%m/%d')),
                ('Aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_certificado.aluno')),
                ('Templates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_certificado.templates')),
            ],
        ),
    ]
