# Generated by Django 4.2.4 on 2023-10-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_certificado', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Templates',
            new_name='Template',
        ),
    ]
