# Generated by Django 4.2.4 on 2023-10-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certificado', '0003_alter_certificado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Adm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='Imagem',
            field=models.ImageField(upload_to='certificados/covers/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='template',
            name='Imagem',
            field=models.ImageField(upload_to='TemplatesCertificado/covers/%Y/%m/%d'),
        ),
    ]
