# Generated by Django 4.2.4 on 2023-10-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certificado', '0005_rename_horas_aluno_horas_rename_nome_aluno_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
