# Generated by Django 4.2.4 on 2023-10-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certificado', '0006_aluno_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='categoria',
            field=models.CharField(max_length=1000),
        ),
    ]
