# Generated by Django 4.2.4 on 2023-11-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_certificado', '0007_alter_certificado_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='horas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='duracao',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='imagem',
            field=models.ImageField(upload_to='certificados/covers'),
        ),
        migrations.AlterField(
            model_name='template',
            name='imagem',
            field=models.ImageField(upload_to='TemplatesCertificado/covers'),
        ),
    ]
